### ISSUE TITLE
confused of the glimpses

### ISSUE THREAD

**Issue by jiujiuxia** [OptMLGroup/VRP-RL#1]
Are the glimpses in the code corresponding to the equation 4 and 5 in the article?
I an quite confused of it.
if so, the M in the equation 5 is the number of glimpses?
I like your paper very much, so I want to know how to realize it.
Thank you ~

**Comment by rezanazari** [comment]
There was a typo in this formula, so it might be the reason for confusion. I fixed it for the final NIPS paper and it will be out in a week or two. If you would like, I can send you the final draft by email.

$M$ is the number of input points. Basically what glimpse does is that it uses the attention vector to compute a linear combination of the source side information, and uses it instead of the hidden state of RNN for computing the probabilities. By this trick, we may add non-linearity to attention mechanism. I tried different settings for the glimpse and it turns out the n_glimpse=0 gives the best solutions, so the results reported are for linear attention. 

Glad to see your interest in the paper. Please let me know if you have further questions.

**Comment by jiujiuxia** [comment]
Waaooo, I am soooo excited that you can reply so quickly!!!!!
I am quite interest in your paper, and want to  try to do some extension work on it. But now encounter some problem.
If you don't mind, please send the final draft to my email : jiujiuxia@qq.com
thank you so much!!!

**Comment by jiujiuxia** [comment]
Thanks for your first reply, and thanks for your final draft, which helps me a lot.

However, I still have some questions related to the  network structure about the paper and code.

1.As for paper at part 3.3 "Attention Mechanism", it seems that equation 4 and 5 compute a vector $ct$ to instead of the hidden state of RNN in equation 6.  Does the combination of equation 4 and 5 realizes the glimpse in this mechanism?

2.As for the code at Class "AttentionVRPActor", I found some variable( d, ld…) were embedded twice here. Why do you code it like this, just for experience? Another, I did not find the parameter $W$ here, and I just found the $v$ here. Why there is no $W$, or you just denote it by another way?

I am somewhat at a mess. I would appreciate it if you could answer my question above.

**Comment by rezanazari** [comment]
I am not quite sure about the first question. Could you elaborate what do you mean by realizing the glimpse mechanism?

About 2, the first transformation maps a number in 1 dimension to another one in a higher dimension. The second weights are used when combining different embedded features which adds more trainable variable and increases the learning capability. I added them just by experimentation. The variables 'W' are defined inside the TF layer components. For example, self.emb_d has a set of weights and biases.

**Comment by jiujiuxia** [comment]
Thank you very much!!!!

About 2, thanks to your detailed explanation, I am quite clearly now !!!!  I did this in my pytorch code, and the result has been greatly improved.  It is so cool!!!

About 1, I am not sure where is the glimpse part in the paper. Is the part in the picture?
and another problem, you said that you turned out the n_glimpse=0 gives the best solutions. In other words, you did not use glimpse in your final result. If so, why do you describe it in your paper? you can just say you use attention mechanism without glimpse.
![glimpse](https://user-images.githubusercontent.com/40752739/49712089-c0c44580-fc7d-11e8-8db9-0bff35602fb3.PNG)


Thank you again for your patient answer!!!!

**Comment by rezanazari** [comment]
Well, $c_t$ is responsible for the glimpse. You can compute $c_t$ and use it instead of $h_t$ while decoding.
